name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  make-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v1.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-snake.gif
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
           # Options
          user: c4th4r5y5
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Montreal
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/5PKdMfYYXjZOHKQr3XeqX5?utm_source=generator
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: .user.login
